CREATE TABLE comment(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    message VARCHAR(255) NOT NULL
)

CREATE TABLE email(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email_address VARCHAR(50) NOT NULL,
    message VARCHAR(255) NOT NULL
)